packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@libsql/client": ^0.18.0
  "@types/node": ^24
  ajv: ^8.20.0
  ajv-formats: ^3.0.1
  better-auth: ^1.7.6
  hono: ^4.13.9
  irisout: ^0.3.0
  kysely: ^0.29.6
  kysely-turso: ^0.1.1
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - irisout@0.3.1 || 0.3.3 || 0.3.4
